# Generated by Django 5.1 on 2024-08-19 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikiApp', '0002_articulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='temaRelacionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wikiApp.tema'),
        ),
    ]
