# Generated by Django 5.1 on 2024-08-19 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikiApp', '0003_articulo_temarelacionado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='nombreTema',
        ),
        migrations.AlterField(
            model_name='articulo',
            name='contenidoArticulo',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='tituloArticulo',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='tema',
            name='descripcionTema',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='tema',
            name='tituloTema',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
